### ISSUE TITLE
Mismatch between requirement versions in setup.py and requirements.txt

### ISSUE THREAD

**Issue by amercader** [ckan/ckan-service-provider#16]
`setup.py` has requirements unpinned:

```
      install_requires=[
            'APScheduler',
            'Flask',
            'SQLAlchemy',
            'requests',
            'flask-admin',
            'flask-login'
      ],
```

`requirements.txt` has (some) requirements pinned:

```
APScheduler==2.0.3
Flask==0.9
SQLAlchemy==0.7.8
requests==0.14.1
flask-admin
flask-login
```

I think they should be pinned and only listed in one place. I don't know how I ended up with APScheduler==3.0.0rc1 which breaks things.

**Comment by davidread** [comment]
>  I don't know how I ended up with APScheduler==3.0.0rc1 which breaks things.

APScheduler<3.0.0 has been specified in setup.py since this was raised.

> I think they should be pinned

The Flask, flask-admin, SQLAlchemy and requests versions shouldn't be pinned, as there are no ckan-service-provider doesn't care which version, but CKAN does, and that has them pinned already.

flask-login is the only one where 0.2 isn't ok but later version are (see https://github.com/ckan/ckan-service-provider/pull/28 ). Should someone encounter this problem, they can use the new requirements.txt, with suggested versions for this and the rest.

> and only listed in one place.

In this case the setup.py covers the majority of cases. The requirements.txt is just a handy backup to use should newer versions of the dependencies have breaking changes. I think that's a reasonable compromise even though it does repeat the names of the modules.
